### ISSUE TITLE
Improve usability of species navigation to locate species listed and their entries on website homepages (Jakavos)

### ISSUE THREAD

**Issue by StephRorke** [BiologicalRecordsCentre/ukotas#12]
- Consider adding an option to drill down using informal groups rather than pure taxonomic groupings, with an option to display common names for groups.
- Consider use of environment (terrestrial / freshwater / marine) groupings for searching, producing lists of species
- If informal groupings are not possible, consider ordering alphabetically and / or increase granularity of taxonomic groups listed.
- Options to download subsets of all the above would be useful

**Comment by johnvanbreda** [comment]
The hierarchy is now alphabetical.

**Comment by StephRorke** [comment]
@DavidRoy it would be good to have your input here, my feeling at present is that all the above related to group informal names is probably more time than we would want to spend at this point. Now there is an option to export to csv this will make the input task of checking easier and these filtering options would be aimed more at the end user and could probably wait until later in the project. I think it would be useful to allow ourselves the flexibility to add this feature in the future, @johnvanbreda I can't access the taxonomy page linked above, would the informal group need to be supplied once per taxon entry in an overall hierarchy or is it on a per species basis, thinking in terms of whether it needs to be added to the input template or not.
I also think it would be worth adding fields to hold environment categories and populate these as we go so we have the flexibility further down the line as it wouldn't be an onerous task at this stage whilst gathering data. 

@johnvanbreda I'm not sure I understand point 5 - tool v. browser - I think the download option as it is at the moment is fine, but imagine that we would want to add a download feature to the browser aimed at the end user later in the project.

**Comment by johnvanbreda** [comment]
@StephRorke I've given you rights to view the taxonomy pages for the Catalogue of Life hierarchy so you can see what I mean - the informal names just need to be applied to the "node" in the hierarchy, e.g. Segmented Worms only needs to be specified once for the Annelid term and the taxa within that branch should be able to pick up the name.

Point 5 was meant as you seem to have worked out - the question being about whether the species browser needs it's own separate tool for downloads.

I'll leave this for now then.

**Comment by StephRorke** [comment]
Re-visiting this issue since the website is no-longer using Catalogue of life. @johnvanbreda could you please advise on options to make the species entries more accessible for the end user? Things we would like to see added include:

- General search box to allow search of common and scientific name and ideally informal group, results to be reflected in grid pane to the right of the hierarchy with clickable links through to the species pages. 
- If users choose to search using hierarchy display species in results pane to right to remove need to click through every taxonomic level to reach the species entry
- Additional feature in left hand pane (along with taxon hierarchy) to allow filtering of species list by other fields from the import template. Changes made here update the main grid to the right displaying species list

Suggestions based on the IUCN Red List search functionality that seems to be the most user friendly I have found. https://www.iucnredlist.org/search

**Comment by johnvanbreda** [comment]
@StephRorke I think all this is possible, the main issue I can see is getting the user interface correct, especially as there is an interaction between the hierarchy view and a new list based view of the species accounts, plus some complexity in the UI for searching in any of the fields. Here's a set of changes which I think gives you what you need:

1. At the top of the screen, as now, a territory select box, plus a search box. However, change the search box so that it searches in any field (species name, common names plus all the other fields combined). I.e. a global search.
2. If you click on a higher level taxon in the hierarchy, the right column is populated with the list of all species under the chosen taxon (just species level). 
3. If you click on a species level taxon in the hierarchy OR in the list on the right column, the right column gets replaced by the species account.

This approach is not as flexible as the IUCN one which has a "filter builder" in the left column, so that taxonomy is just one way to browse through the data. We could copy this approach, with taxonomy in a section you need to expand, but you could also expand a section to select by habitat, establishment status or any of the other fields.

A further thought is we could display a gallery of panels in the list view, instead of a plain list of species names. But this would work much better if we added a photo to every species (technically that's OK, but sourcing and populating all the photos may be difficult of course).

I've got approx. 2 days left on the current contract so can work on this - I think it's enough to do most of the 3 listed points,  or at least get to a proof of concept, but excluding designing a filter builder like the IUCN one.

**Comment by StephRorke** [comment]
@johnvanbreda I think the changes you suggest would improve the user experience greatly, particularly if you can also add features to select by fields other than taxon hierarchy as I expect this is ultimately how the dataset will be explored, e.g. to select all species from a territory with negative impacts, or view a list of all established species. 
As much at it would be nice to add a gallery view, I don't think we have the time to source these on this project so that wouldn't be a priority at this stage. 
Please could you also quote to add a filter builder and I can see what funds are available on the project? Thanks

**Comment by johnvanbreda** [comment]
Hi @StephRorke - would you like me to progress with the changes that I can do using the current available time (i.e. points 1 to 3)? It would make it easier for me to quote accurately for a "filter builder" if I had spent a little bit of time working in this area of the code again. If you need an estimate more quickly though let me know and I'll do my best.

Also, at some point we should plan to move the site to a live URL, rather than using the Pantheon dev staging site - that would give me the option of using the staging sites to demonstrate new functions whilst you test them before they go live.

**Comment by StephRorke** [comment]
@johnvanbreda I'm just waiting for Helen to ok it, hoping to confirm in the next 24 hours as Helen is away at present, but i expect to progress with this. 
Can you let me know what is involved in moving it to a live URL as I would also prefer to have a dev and live site, especially as it may well be used in workshops etc. Thanks

**Comment by johnvanbreda** [comment]
@StephRorke I can create a test and live version of the site - that's quite easy, but the URL will be the same as the current one with "dev" replaced by "test" or "live". Biren can assist you with the steps required for using a proper domain to point to the live site (if you need to). The main issue will be letting any current users know that they should start to use the live version of the site rather than dev - are there many people you'd need to notify? We don't want to create the live version of the site only to find that some data has been added afterwards on the test version.

**Comment by StephRorke** [comment]
@johnvanbreda - it's only being used internally at present.

**Comment by johnvanbreda** [comment]
Are any of the current users adding data at present? If so, is there a convenient time for them to stop? If not, I can just create the test and live site then send you the new URL to give out.

**Comment by StephRorke** [comment]
@johnvanbreda no plans for any data to be added in the next week.

**Comment by StephRorke** [comment]
@johnvanbreda Helen has confirmed she is happy for you to go ahead and progress the search functionality.

**Comment by johnvanbreda** [comment]
@StephRorke Ok, will do. I've initialised the live site now - please can you tell everyone that they should use https://live-ceh-ukotas-d10.pantheonsite.io from now on. You can use https://test-ceh-ukotas-d10.pantheonsite.io if you want to experiment with adding content but anything you add here will be lost at some point and won't go onto the live site. I will use https://dev-ceh-ukotas-d10.pantheonsite.io for my development efforts.

**Comment by StephRorke** [comment]
Thanks @johnvanbreda - I'll let everyone know.

**Comment by johnvanbreda** [comment]
@StephRorke there is now a test view page at https://searchdev-ceh-ukotas-d10.pantheonsite.io/browse-species which has some new functionality - it shows a list of all selected species beneath a higher taxon, and the search is now global, not just on the species name field, so you can search for Established for example (though it will find it in any notes field). I'll get back to you with thoughts on a more advanced IUCN style search tool.

**Comment by StephRorke** [comment]
@johnvanbreda thank you - this looks immediately more accessible for the end user. I look forward to seeing how we can add to the filter layers e.g. establishment status or impact, and also including the import of informal group names - Meg now has some datasets with the NBN groupings applied, could the import template on the test site be updated to include this?

**Comment by johnvanbreda** [comment]
I've added a new issue for a discussion on group name addition (#33) so this issue stays focused on the search functionality.

@StephRorke do you want me to enable the new functionality on the live site search as it is?

I will send a costing for the search tool filtering by different fields in a moment.

**Comment by StephRorke** [comment]
@johnvanbreda if you were able to make one change so that when you added a new search term the right pane cleared then yes I think it would be great to have this on the live site. For example if I add 'worm' and click on the taxon hierarchy so the right hand pane is populated with a list of species including 'worm' and then add beetle to the search box and click apply the taxon hierarchy updates but the right hand pane is still populated with my 'worm' species. Is this a quick update? Thanks

**Comment by johnvanbreda** [comment]
@StephRorke I've done that and deployed to live. You may have to clear your browser cache to get the latest scripts. I'll close this issue now and add a new one for development of the faceted search.
